#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#homepage_redirect:
#    path: /
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
#    defaults:
#        route: contact_index
#        permanent: true

homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    welcome.html.twig